name: C Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        shell: bash
        run: |
          gcc main.c core/*.c security/*.c system/*.c storage/*.c ui/*.c -o hihi.exe

      - name: Verify executable
        shell: bash
        run: |
          test -f hihi.exe
